### ISSUE TITLE
//check_cisco_stack.py// Error "ValueError: zero length field name in format"

### ISSUE THREAD

**Issue by aadiaz7** [ziesemer/wershlak-nagios_plugins#1]
** check_cisco_stack.py **

I was testing the updated script in a RHEL box with Nagios and i keep receiving the following error:

![image](https://cloud.githubusercontent.com/assets/24277816/20766398/1b0edd9e-b715-11e6-8ad6-4be5b8feec29.png)

Python version: 2.6.6
OS: Red Hat Enterprise Linux Server release 6.7 (Santiago)
Nagios Version: 4.2.0

I think that is related with the Python version i have installed in my BOX, is there any workaround that u've been working regarding this issue?.

Cheers,

**Comment by ziesemer** [comment]
Fixed.  If I had been consistent with the format strings, this would not have happened.  My previous testing was done in Cygwin, and CentOS 7 - both of which were running Python 2.7 versions, which allows for omitted positional argument specifiers.  From https://docs.python.org/2/library/string.html#format-string-syntax:

> Changed in version 2.7: The positional argument specifiers can be omitted, so '{} {}' is equivalent to '{0} {1}'.
