### ISSUE TITLE
Returns WARNING state when checking 1 member stacks

### ISSUE THREAD

**Issue by gollumsss** [ziesemer/wershlak-nagios_plugins#2]
Tested on 2960X & 2960S stacks, it should return OK when checking 1 member stacks.

**Comment by gollumsss** [comment]
Returns:  "WARNING - 1 Members:: 1: ready, Stack Ring is non-redundant"

I think it should skip stack ring checks when detecting 1 member stacks, there is no point.

**Comment by ziesemer** [comment]
Why not just skip the check on non-stacked devices?  I'd be concerned that a stack should have existed and didn't for some reason (misconfiguration, or incorrect install, etc.) - and then the check would not serve any benefit to detecting that...

**Comment by gollumsss** [comment]
We have a mixed environment (university campus) checked with nagios, its easier for us to implement the check in all stackable switches in our nagios environment.

**Comment by ziesemer** [comment]
@gollumsss - with the 1.5 version just committed, there is no functional difference by default - as I or others may be relying upon the existing functionality.  For your case, you could now add the following to your check command line:

    --stack-size [,]

... which is short-hand for:

    --stack-size [-inf,inf]

... which will effectively accept any stack size.  A simple fixed number is also accepted:

    --stack-size 5

... or a given range / interval:

    --stack-size [2,5]

The solution may have been a bit of an overkill here, but was done in mind with future re-use - for here, other monitoring needs, or other Python work in general.  Any number accepted by Python's [`float`](https://docs.python.org/2/library/functions.html#float) function is acceptable - including `inf`, `-inf`, etc.  The range / interval notation follows that as described at https://en.wikipedia.org/wiki/Interval_%28mathematics%29#Notations_for_intervals - while using `-inf`/`inf` as defaults for blank values, respectively.
